return {
  "catppuccin/nvim",
  name = "catppuccin",
  priority = 1000,
  opts = {
    transparent_background = true,
    integrations = {
      aerial = true,
      alpha = true,
      barbar = true,
      beacon = true,
      blink_cmp = {
        enabled = true,
        style = "bordered",
      },
      buffon = true,
      coc_nvim = true,
      colorful_winsep = {
        enabled = true,
        color = "red",
      },
      cmp = true,
      dashboard = true,
      diffview = true,
      dropbar = {
        enabled = true,
        color_mode = false,
      },
      fern = true,
      fidget = true,
      flash = true,
      fzf = true,
      gitgraph = true,
      gitsigns = {
        enabled = true,
        transparent = true,
      },
      grug_far = true,
      harpoon = true,
      headlines = true,
      hop = true,
      indent_blankline = {
        enabled = true,
        scope_color = "lavender",
        colored_indent_levels = false,
      },
      leap = true,
      lightspeed = true,
      lsp_saga = true,
      lir = {
        enabled = true,
        git_status = false,
      },
      markdown = true,
      markview = true,
      mason = true,
      mini = {
        enabled = true,
        indentscope_color = "",
      },
      neotree = true,
      neogit = true,
      neotest = true,
      noice = true,
      notifier = true,
      notify = true,
      nvimtree = true,
      nvim_surround = true,
      native_lsp = {
        enabled = true,
        virtual_text = {
          errors = { "italic" },
          hints = { "italic" },
          warnings = { "italic" },
          information = { "italic" },
          ok = { "italic" },
        },
        underlines = {
          errors = { "underline" },
          hints = { "underline" },
          warnings = { "underline" },
          information = { "underline" },
          ok = { "underline" },
        },
        inlay_hints = {
          background = true,
        },
      },
      navic = {
        enabled = false,
        custom_bg = "NONE",
      },
      semantic_tokens = true,
      treesitter = true,
      treesitter_context = true,
      window_picker = true,
      render_markdown = true,
      telescope = {
        enabled = true,
      },
    },
  },
}
